#!/bin/bash
# Generate C souce code (an byte array) from binary file.

# Check input arguments
if [ $# -ne 2 ]; then
    echo "Usage: $0 <input_binary_file> <output_c_source_file>"
    exit 1
fi

input_file=$1
output_file=$2

if [ ! -f "$input_file" ]; then
    echo "Error: Input file '$input_file' not found!"
    exit 1
fi

if [ -f "$output_file" ]; then
    rm -rf $output_file
    echo "$output_file is removed"
fi

touch $output_file
if [ $? -ne 0 ]; then
    exit 1
fi

# generate content of the output file
echo "// Generated by $(basename $0) on $(date) - do not edit" > $output_file
echo "#include \"types.h\"" >> $output_file
echo "" >> $output_file
echo "uchar initcode[] = {" >> $output_file
# Hex dump of input file and format it.
{
    od -v -t xC "$input_file" | awk '{
        # Remove heading address
        $1="";
        
        # Process each byte
        for (i=2; i<=NF; i++) {
            $i = "0x" $i ",";
        }
        
        # Print the processed lines
        print $0;
    }' | sed 's/^ *//'  # Remove extra spaces at the beginning of the line
} >> "$output_file"
echo "};" >> $output_file
echo "" >> $output_file
echo "int sizeof_initcode = sizeof(initcode);" >> $output_file

echo "$output_file is generated!"
